version: '3.8'
services:
  app:
    image: spring-boot-jwt-app
    build: .
    ports:
      - "8005:8005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pura_CRM
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: pura_CRM
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: